language: java

jdk:
    - oraclejdk8

before_install:
    - echo "$GPG_SECRET_KEYS" | base64 --decode | "$GPG_EXECUTABLE" --import
    - echo "$GPG_OWNERTRUST" | base64 --decode | "$GPG_EXECUTABLE" --import-ownertrust

install:
    - mvn -Prelease -s .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B

deploy:
    - provider: script
      script: .travis/deploy.sh
      on:
          branch: master
    - provider: script
      script: .travis/deploy.sh
      on:
          branch: releases/*

after_success:
    - mvn clean test jacoco:report coveralls:report
