language: java

jdk:
    - oraclejdk8

before_install:
    - echo "$GPG_SECRET_KEYS" | base64 --decode | "$GPG_EXECUTABLE" --import
    - echo "$GPG_OWNERTRUST" | base64 --decode | "$GPG_EXECUTABLE" --import-ownertrust

install:
    - gpg -q --passphrase "$GPG_PASSPHRASE" -d .travis/deploy-ssh-keys.tar.gpg | tar xf - -C $HOME/.ssh
    - mvn -B -Prelease -s .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true

deploy:
    - provider: script
      script: .travis/deploy.sh
      on:
          branch: master
    - provider: script
      script: .travis/deploy.sh
      on:
          branch: releases/*

after_success:
    - mvn -B clean test site jacoco:report coveralls:report
